### ISSUE TITLE
Update README.md Installation

### ISSUE THREAD

**Issue by alvarotorrestx** [alvarotorrestx/DevConnect#2]
- Add steps on forking the project
- Add installation for frontend
- Add installation for backend
- Run

**Comment by medelm1** [comment]
Hey, @alvarotorrestx, could you please assign this to me?

**Comment by alvarotorrestx** [comment]
@medelm1 Sure, I was going to work on it, but go for it!

**Comment by medelm1** [comment]
I'll take care of it.

**Comment by alvarotorrestx** [comment]
@medelm1 great work and thanks again for contributing! Keep an eye out, I'll be adding more issues and working on more for this project throughout the week! 😊
